---
abstract: 'Multiple SQL statements in a single do() call with any DBI driver'
author:
  - 'Emanuele Zeppieri <emazep@cpan.org>'
build_requires:
  DBD::SQLite: 0
  DBI: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0.27
  Test::More: 0.7
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.110360'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-MultiStatementDo
requires:
  Carp: 0
  Moose: 0
  SQL::SplitStatement: 1.00000
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-MultiStatementDo
  homepage: http://search.cpan.org/dist/DBIx-MultiStatementDo
  repository: git://github.com/emazep/DBIx-MultiStatementDo.git
version: 1.00000
